apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: dev/helm-charts
      version: '1.0.x'
      sourceRef:
        kind: GitRepository
        name: bk.secretum
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
