---
- op: add
  path: /metadata/annotations/meta.helm.sh~1release-name
  value: "test"

- op: replace
  path: /spec/rules/0/host
  value: staging.notesapp.plan.com

- op: replace
  path: /spec/rules/1/host
  value: www.staging.notesapp.plan.com