apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: application-charts
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: helm-chart
  secretRef:
    name: flux-system
  url: ssh://git@github.com/MustafinAlex/bk.flux