{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-release.fullname" . }}
  labels:
    {{- include "helm-release.labels" . | nindent 4 }}
data:
{{- range $path, $config := .Values.configMap }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}
