---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "helm-release.fullname" . }}
  labels:
    name: {{ include "helm-release.fullname" . }}
    {{- include "helm-release.labels" . | nindent 4 }}
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "helm-release.fullname" . }}
  targetCPUUtilizationPercentage: 60
