---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/application
  - ../../base/ingress-external
  - ../../base/ingress-nginx

patches:

  - path: ./patches/ingress-external.yaml
    target:
      kind: Ingress
      version: v1
      namespace: ingress-nginx
      name: ingress-nginx-external
