---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-mosaic-dev-eks
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./mosaic-dev-eks
  prune: true
  sourceRef:
    kind: GitRepository
    name: bk.k8s-apps



