apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bop-config-ui
  namespace: application
spec:
  interval: 5m
  chart:
    spec:
      chart: application/base/helm-charts
      version: '4.0.x'
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: bop-config-ui-values
    valuesKey: values.yaml
    optional: false

#  values:
#    replicaCount: 1
