---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - bop-config-api-k.yaml
#  - bop-config-ui.yaml
#  - bop-config-api.yaml

# For test (Renaming Namespace)
patches:
  - path: ./patches/global/namespace.yaml
    target:
       kind: Namespace
       metadata:
         name: whatever
---
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: bop-config-api
  namespace: flux-system
spec:
  interval: 1m0s
  path: mosaic-dev-eks/bop-config-api/
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-apps

