apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appllication
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./helm-charts
      version: '4.0.x'
      sourceRef:
        kind: GitRepository
        name: flux-system
      interval: 1m
#  valuesFrom:
#  - kind: ConfigMap
#    name: bop-config-invoice-search-ui-values
#    valuesKey: values.yaml
#    optional: false
#  values:
#    replicaCount: 1
