---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-mosaic-dev-eks
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./application/overlays/mosaic-dev-eks
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
