---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: application
  namespace: flux-system
spec:
  interval: 10m0s
#  path: ./application/overlays/mosaic-dev-eks
  path: ./application/base/application
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
