apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: msteams
  namespace: flux-system
spec:
  type: msteams
  channel: General
  secretRef:
    name: flux-msteams-url
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: msteams
  namespace: flux-system
spec:
  summary: "Cluster addons impacted in us-east-2"
  providerRef:
    name: msteams
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: '*'
