apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: msteams
  namespace: flux-system
spec:
  type: msteams
  channel: General
  secretRef:
    name: flux-msteams-url
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: msteams
  namespace: flux-system
spec:
  summary: "Cluster pods impacted in DEV cluster"
  providerRef:
    name: msteams
  eventSeverity: error
  eventSources:
    - kind: HelmRelease
      name: '*'
      namespace: application
    - kind: Kustomization
      name: '*'
    - kind: HelmChart
      name: '*'
      namespace: flux-system


