---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      replicaCount: 1
      service:
        targetPorts:
          http: http
          https: http
      config:
        allow-snippet-annotations: "true"
        enable-underscores-in-headers: "true"
        proxy-buffer-size: "64k"
        use-gzip: "true"
        proxy-body-size: "50m"
