apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bop-config-invoice-search-ui
  namespace: applications
spec:
  interval: 5m
  chart:
    spec:
      chart: applications/base/helm-charts
      version: '4.0.x'
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
#  values:
#    replicaCount: 1
